### ISSUE TITLE
关于代码中Q曲线拟合的几个问题

### ISSUE THREAD

**Issue by Mashiro-Sorata** [Janowei/Machine-Learning-Assisted-Inductor-Synthesis#1]
大佬你好，首先感谢您分享的项目。我仔细拜读了一下您的论文，有以下几个疑惑，希望能得到您的答惑。

## 1、代码中的Q值曲线拟合公式与论文中的不一致
论文中为：
$`Q(f)=\tilde{Q} _{max} \cdot sin(\frac{\pi f^{\tilde{F}_{Q_{max}}}}{\tilde{F}_{SRF}^{\tilde{F}_{Q_{max}}}}  )`$
而在本仓库的[代码](https://github.com/Janowei/Machine-Learning-Assisted-Inductor-Synthesis/blob/main/build_model.m)中为高斯曲线去拟合Q值曲线。
这是因为代码版本是早期版本，还是有其他一些原因呢？

## 2、下面[代码](https://github.com/Janowei/Machine-Learning-Assisted-Inductor-Synthesis/blob/main/build_model.m)的`num` 切片位置是否有误？
```matlab
[~,numQmax] = max(Output.Q);
num = find(Output.Q(numQmax:end)<0,1);
if isempty(num) == 1
    num = length(Output.freq);
end
minQ = min(Output.Q);
FitQ = fit(Output.freq(1:num),Output.Q(1:num)-minQ,'gauss1');
```
代码首先找到Q值最大值的下标位置`numQmax`，然后再从最大Q值位置`numQmax`到`end`找到Q值小于0的第一个下标位置。
按理说这里找到的位置是为`Output.Q`的下标位置，但是因为`find`函数中的`Output.Q`进行了切片操作，因此`find`函数返回的为`Output.Q(numQmax:end)`的下标位置。而`fit`函数中再对`Output.freq`和`Output.Q`进行`(1:num)`的切片，感觉就不太对了。

比如以下例子，假设Q的数据为：
```matlab
>> Q = [1:10 10:-1:1 -1:-1:-10]

Q =

     1     2     3     4     5     6     7     8     9    10    10     9     8     7     6     5     4     3     2     1    -1    -2    -3    -4    -5    -6    -7    -8    -9   -10

>> [~,numQmax] = max(Q)

numQmax =

    10

>> num = find(Q(numQmax:end)<0,1)

num =

    12

>> Q(1:num)

ans =

     1     2     3     4     5     6     7     8     9    10    10     9
```
但是根据论文中描述，我们想要的应该是Q值>0的部分：
```matlab
>> Q(1:num+numQmax-2)

ans =

     1     2     3     4     5     6     7     8     9    10    10     9     8     7     6     5     4     3     2     1
```
**所以这部分的代码是否有误呢？**

## 3、拟合中为何减去Q的最小值？
在上面Q值拟合代码中，拟合的参数y不是Q值，而是`Output.Q(1:num)-minQ`，减去了一个minQ。
但是这个`min(Output.Q)`操作时又没有对Q值的范围进行切片限定，导致minQ可能为一个负数。
**请问一下这个操作是出于何种考量呢？**
```matlab
minQ = min(Output.Q);
FitQ = fit(Output.freq(1:num),Output.Q(1:num)-minQ,'gauss1');
```

---

### 再次感谢您，期待您的回复！

**Comment by Janowei** [comment]
同学你好，免佬姓菜，抱歉这么晚回复：
第一个问题：这个版本确实是很早期的版本，由于文章中OSIAS的版权在某家公司手里，我们无法直接开源改版本的代码，因此用早期的版本来替代。在初版中，Q值是用高斯函数进行特征值提取的，但后来我发现该函数无法准确描述Q值的特性，因此后面对其进行了修正，请以文章为准。
第二个问题：该处确实为一个Bug，理论上应该为num+numQmax才对。
第三个问题：为什么要这么做的原因我记不太清了，不过按照文章中的公式是不需要这么做的哦

最后，如果你还有任何问题，欢迎与我联系
顺颂  时琪

**Comment by Mashiro-Sorata** [comment]
> 同学你好，免佬姓菜，抱歉这么晚回复：
> 第一个问题：这个版本确实是很早期的版本，由于文章中OSIAS的版权在某家公司手里，我们无法直接开源改版本的代码，因此用早期的版本来替代。在初版中，Q值是用高斯函数进行特征值提取的，但后来我发现该函数无法准确描述Q值的特性，因此后面对其进行了修正，请以文章为准。
> 第二个问题：该处确实为一个Bug，理论上应该为num+numQmax才对。
> 第三个问题：为什么要这么做的原因我记不太清了，不过按照文章中的公式是不需要这么做的哦
> 
> 最后，如果你还有任何问题，欢迎与我联系
> 顺颂  时琪

非常感谢您的回复！
